### PR TITLE
Show album year

### PR DESCRIPTION
**Pull request by gjedeer**
I'm not convinced this looks good but the info is useful when you want to listen to the latest album by someone.

### CODE REVIEW

**Comment by funkyg** [comment]
yes it makes sense, but it really is a bit ugly, especially if the album title contains "(Deluxe Edition)" or something like that. 

how about putting the year in a seperate textview, eg below the artist, or to the right of the artist?

**Comment by funkyg** [comment]
how about we change this to show the year like "artist | year"?

**Comment by funkyg** [comment]
i changed the design a bit, what do you think?
screenshot

**Comment by gjedeer** [comment]
Looks awesome!

**Pull request merged**
