### PR TITLE
close button on notification (fix 20)

### PR DESCRIPTION
**Pull request by funkyg**
clicking the button closes the notification, but the app stays open. also the service keeps running, and you can start playing again by clicking on a song or album.

functionality should be done, just need to finish the design.

### CODE REVIEW

**Comment by gjedeer** [comment]
Found a small bug:

Clicked that X button when a tune was playing. The notification is gone, player in app is in "playing" state (the pause button displayed) but not playing. Clicking pause, then play, does nothing.

**Comment by funkyg** [comment]
oh right, i have to add a callback for that. should we hide the bottom bar in that case, or just set it to paused?

**Comment by gjedeer** [comment]
Paused maybe?

On 7 June 2017 06:15:08 CEST, funkyg <notifications@github.com> wrote:
>oh right, i have to add a callback for that. should we hide the bottom
>bar in that case, or just set it to paused?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/funkyg/funkytunes/pull/27#issuecomment-306681756

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by funkyg** [comment]
okay i just updated the design, and made it so the bottom bar is hidden when you close the notification (i think thats the easiest option). Should be good to merge now.

**Pull request merged**
